package controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class SampleController {

	// Event Listener on Button.onAction
	@FXML
	public void abrirInforme(ActionEvent event) {
		// TODO Autogenerated
	}
}
