package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

public class VentanaController {
	@FXML
	private ToggleGroup tipo;
	@FXML
	private ToggleGroup tipo1;
	@FXML
	private ToggleGroup tipo11;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
